Repository Comp367Project/Final-Project, pull requests merged in 2023-04, with the labels that each got.

#3 updated readme.md
  README.md
Labels: documentation

#8 close #4 gunicorn setup files has been added
  gunicorn.service
  gunicorn.sh
  gunicorn.socket
Labels: bug

#9 close #5 - added envsetup.sh
  envsetup.sh
Labels: bug

#10 close #6 - added app.conf file
  app.conf
Labels: bug

#14 close #12 - added jenkins file - feature1
  Jenkinsfile
Labels: enhancement

#19 fixed #17 - added jenkins file - bug1
  web_site/settings.py
Labels: bug
